//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeraJenkins.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DialogStep
    {
        public long Id { get; set; }
        public long UserDialogId { get; set; }
        public int StepNum { get; set; }
        public string Value { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual UserDialog UserDialog { get; set; }
    }
}
