//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeraJenkins.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TgEntities : DbContext
    {
        public TgEntities()
            : base("name=TgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GamePlayer> GamePlayer { get; set; }
        public virtual DbSet<GameRegistration> GameRegistration { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<GameRegistrationUnfinished> GameRegistrationUnfinished { get; set; }
        public virtual DbSet<UserAction> UserAction { get; set; }
        public virtual DbSet<Dialog> Dialog { get; set; }
        public virtual DbSet<DialogStep> DialogStep { get; set; }
        public virtual DbSet<UserDialog> UserDialog { get; set; }
    }
}
