//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeraJenkins.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDialog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserDialog()
        {
            this.DialogStep = new HashSet<DialogStep>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public long DialogId { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
    
        public virtual Dialog Dialog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DialogStep> DialogStep { get; set; }
        public virtual User User { get; set; }
    }
}
