//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeraJenkins.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewMemberMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewMemberMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeraJenkins.Resources.NewMemberMessages", typeof(NewMemberMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to привет, {0} !{3}как дела? а расскажи про свои любимые игры? Во что играешь чаще всего?{3}Мы тут частенько собираемся поиграть, в &lt;a href=&quot;{1}&quot;&gt;Табличке&lt;/a&gt; обычно записываемся на будущие встречи. Жду тебя! ;){3}Вот здесь &lt;a href=&quot;{2}&quot;&gt;ответы на все вопросы&lt;/a&gt; , а ещё можешь написать мне в личные сообщения, я помогу записаться на игры).
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, хэй, здарова!{3}надо пройти обряд посвящения – рассказать про пару-тройку своих любимых настолочек) тут так принято.{3}А ещё у нас принято иногда собираться да и поиграть в них) Вот в этой &lt;a href=&quot;{1}&quot;&gt;Табличке&lt;/a&gt; мы записываемся на игровечера!{3}А вот тут &lt;a href=&quot;{2}&quot;&gt;Инструкция&lt;/a&gt;, где я отвечаю на все основные вопросы){3}Напиши мне в личку, если нужна помощь в записи на игры).
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to приветик, {0} ){3}а мы тут настолочками балуемся. Какие у тебя любимые? Присоединяйся, мы иногда собираемся и вечерами играем) Вот тут наша &lt;a href=&quot;{1}&quot;&gt;Табличка&lt;/a&gt;, посмотри, что там интересного предлагают ){3}Вкратце о нас, и что тут происходит – вот &lt;a href=&quot;{2}&quot;&gt;Инструкция&lt;/a&gt;.{3}Нужна помощь в записи на игры – пиши мне в личку, разберёмся)).
        /// </summary>
        public static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ого, кто у нас тут!) {0} !{3}я тебя где-то видела… хм. А расскажи, какие настольные игры тебе нравятся? Со мной вот только в Манчкин играют :({3}А ещё мы собираемся по четвергам поиграть, вот тут &lt;a href=&quot;{1}&quot;&gt;Табличка&lt;/a&gt; с записью на игры.{3}Небольшая презентация о нас – смотри &lt;a href=&quot;{2}&quot;&gt;FAQ&lt;/a&gt;.{3}А ещё можешь написать мне в личку, помогу выбрать игру и записаться на неё ).
        /// </summary>
        public static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, привет){3}мы тут всех новичков просим посоветовать хорошие настольные игры, что у тебя есть на примете? ){3}Может, заодно и принесёшь их на наши игровые вечера? Вот &lt;a href=&quot;{1}&quot;&gt;тут&lt;/a&gt; можно посмотреть, что приносят остальные){3}А &lt;a href=&quot;{2}&quot;&gt;здесь&lt;/a&gt; ты найдёшь все основные вопросы и ответы){3}Я помогу тебе записаться на игру, если напишешь мне в личку ;).
        /// </summary>
        public static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветики, {0} ){3}спаси меня, они меня все тут убеждают, что Монополия – плохая игра(( у тебя есть что-нибудь подобное, но чтобы не было стыдно?{3}кстати, можешь заодно вот &lt;a href=&quot;{1}&quot;&gt;тут&lt;/a&gt; посмотреть, что наши ребята приносят на игровые вечера. И тоже приходи )){3}Смотри, а ещё &lt;a href=&quot;{2}&quot;&gt;здесь&lt;/a&gt; ты найдёшь все основные вопросы и ответы){3}И напоследок: напиши мне в личку, если требуется помощь в записи на игры ;).
        /// </summary>
        public static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to приветик, {0}! Во что играешь обычно?{3}вот &lt;a href=&quot;{1}&quot;&gt;здесь&lt;/a&gt; у нас планы на ближайшие игровые вечера ) придёшь?{3}Вот &lt;a href=&quot;{2}&quot;&gt;тут&lt;/a&gt; ты найдёшь все основные вопросы и ответы){3}Ну и можешь написать мне в личку, я помогу с записью на игры).
        /// </summary>
        public static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, здравствуй!{3}Смотри, у меня есть &lt;a href=&quot;{1}&quot;&gt;ссылка,&lt;/a&gt; где все записываются на игровые вечера, а ты мне давай в ответ свои любимые настольные игры)){3}Если возникнут вопросы, &lt;a href=&quot;{2}&quot;&gt;тут&lt;/a&gt; есть на них ответы){3}А ещё я могу помочь записаться на игру и напомнить о ней заранее) ты только напиши мне в личные сообщения….
        /// </summary>
        public static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, о, ещё один новичок! ну привет. Проходи, присаживайся. У нас тут клуб анонимных настольщиков. {3}Во что играешь, во что хочется сыграть? Обычно по четвергам у нас сборы в баре Guns&amp;Bears, приходи, сыграем!) вот &lt;a href=&quot;{1}&quot;&gt;тут&lt;/a&gt;  можно записаться на что-то определённое!{3}Если есть вопросы - &lt;a href=&quot;{2}&quot;&gt;здесь&lt;/a&gt; ты найдёшь все ответы на них){3}Напиши мне в личку, я помогу выбрать игру для записи).
        /// </summary>
        public static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to налетай на новичка! ) {0}{3}приходи на ближайший игровечер – у нас никто не кусается, правила настольных игр объясняют ) обычно собираемся по четвергам на Новослободской. Придёшь? вот &lt;a href=&quot;{1}&quot;&gt;тут&lt;/a&gt; запись ) ждём!{3}p.s. если возникнут вопросы – ищи ответы &lt;a href=&quot;{2}&quot;&gt;здесь&lt;/a&gt;.{3}А ещё можешь написать мне в личку – я подскажу, как записаться на игры ;).
        /// </summary>
        public static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
